---
title: "GEO546: Global Change Ecology"
subtitle: "Global Change Ecology"
---

Professor <a href="http://adamwilson.us"> Adam M. Wilson </a><br>
Instructor <a href="https://sites.google.com/view/yingyingxie/home"> Yingying Xie </a><br>
Department of Geography, & Graduate Program in Evolution, Ecology and Behavior <br> 
University at Buffalo, Buffalo, NY

## Description
Global environmental change has significant impacts on social and ecological systems around the world.  Global Change Ecology is an emerging field that aims to understand the ecological implications of environmental change (especially anthropogenic climate change) and to assess risks under future global change. The course will include lectures, discussions of important scientific articles, hands-on exercises in conducting scientific research, and a group project to investigate novel scientific questions. In this course, students will review the basics of the earth system and climate change before investigating how organisms in terrestrial and aquatic ecosystems respond to climate change. Finally, we will consider the impacts of future climate change and the implications for conservation policy and adaptation management. 
